feat:디자인 토큰 추가
Seoul-Woman-Hackathon/kids-guardian-front pull request #2
Opened 2023-07-26 12:24 UTC by JjungminLee

#1 
- 디자인 토큰 추가
- navbar (제작중)
- pr템플릿 작성
- 소나님 께서 요청해주셨던 폴더구조 작업

2023-08-01 12:44 UTC, ballsona requested changes

2023-08-01 12:44 UTC, ballsona commented on tsconfig.json
> +>>>>>>> 21e9849f65e6e0bb9596dabea53494c500014830
정민님 요부분은 수정이 조금 필요해보여요!

2023-08-01 15:06 UTC, JjungminLee commented on tsconfig.json
> +>>>>>>> 21e9849f65e6e0bb9596dabea53494c500014830
넵 그 부분 다시 수정해놨어요! 근데 제가 저거말고도 저 부분에 손본게 많아서 아마 충돌이 또 날 수도 있는데 그러면 제가 수동으로 또 수정해두겠습니다!

2023-08-02 03:11 UTC, ballsona approved these changes
LGTM 👍

2023-08-02 03:11 UTC, merged